### ISSUE TITLE
psar not listening to parameters

### ISSUE THREAD

**Issue by danray0424** [TulipCharts/tulipnode#10]
The following code should, I believe, produce quite different values for the resulting next-most-recent PSAR (last closed candlestick):
    
    console.log("current price " + currentprice);
    tulind.indicators.psar.indicator([high, low], [.02, .025], function(err, results) {
        sar = results[0];
        console.log("with parameters .02 - .025: " + sar[1]);		  		
    });	
    tulind.indicators.psar.indicator([high, low], [.04, .05], function(err, results) {
        sar = results[0];
        console.log("with parameters .04 - .05: " + sar[1]);		  		
    });	
    tulind.indicators.psar.indicator([high, low], [.1, .2], function(err, results) {
        sar = results[0];
        console.log("with parameters .1 - .2: " + sar[1]);		  		
    });	
    tulind.indicators.psar.indicator([high, low], [1, 2], function(err, results) {
        sar = results[0];
        console.log("with parameters 1 - 2: " + sar[1]);
    });	

However, the output I get is:

```
current price 42.66
with parameters .02 - .025: 42.67
with parameters .05 - .04: 42.67
with parameters .1 - .2: 42.67
with parameters 1 - 2: 42.67
```

Is this broken, or am I going wrong somewhere?

**Comment by codeplea** [comment]
Your code seems to only be looking at the second bar returned (which corresponds to the third bar of input, in this case). You say you're looking at the next-most-recent, but `results[0][1]` is the next-least-recent. Psar is also the kind of indicator that will vary depending on how much history you give it (because giving more history will change the starting point). Basically, the starting point for psar is kind of arbitrary and worthless. The indicator is useful after developing for a while.

Now, one thing to know about how psar works, is that it does "reversals". At each reversal, the output is reset to a recent "extreme point" which is just a recent high or low. At these reversal points, the acceleration factor options mean nothing. I'm guessing that the bar you are looking at is on one of these reversal points.

The definitive reference for calculating parabolic stop and reverse is [Wilder, J. Welles (1978) New Concepts in Technical Trading Systems](http://www.amazon.com/exec/obidos/ASIN/0894590278/tulind-20). Another good reference is [Achelis, S. (2000) Technical Analysis from A to Z, 2nd Edition](http://www.amazon.com/exec/obidos/ASIN/0071363483/tulind-20).

Tulip Indicators was tested pretty thoroughly, but if you still think there is a bug you should post the `high` and `low` arrays here and we can do the calculation by hand. You should also post the entire `results[0]` array too.

You can see the [C code for the psar function here](https://github.com/TulipCharts/tulipindicators/blob/cea7ea23af0145c92f2b40f84f9c5aa30bc6df97/indicators/psar.c).

**Comment by codeplea** [comment]
Another thing about psar is that in a long position the output can't be more than previous bar's low, and in a short position it can't be less than the previous bar's high. You might be looking at an output where it's clamping on that.

Really there's a lot of things that could be happening. We'll need to see your `high` and `low` arrays to know.

**Comment by danray0424** [comment]
Interesting. I have wondered if I'm confused about the time series order. The docs don't say--should the input arrays be in increasing order of time, or decreasing? Soonest-first or soonest-last, in other words?

**Comment by codeplea** [comment]
Earliest and oldest data first. Most-recent and newest data last. I guess I should make that clear somewhere in the docs.
