### ISSUE TITLE
Want to use the library but can't get it working on mac

### ISSUE THREAD

**Issue by dexcell** [TulipCharts/tulipnode#5]
After `npm install`
````
node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.6/Release/tulind-v0.8.6-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.6 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)
g
```

Any idea how to fix on osx?

Thanks

**Comment by codeplea** [comment]
That message is simply saying that pre-built binaries weren't found for OSX, which is normal because I don't offer them (currently the binaries are only available for Windows). On OSX, it should then continue to compile from source and work normally.

You can use the command `npm install --build-from-source` if you want to avoid the message.

What happened after that message? Did it continue to compile normally?

For reference, [here is what a successful install looks like on OSX](https://travis-ci.org/TulipCharts/tulipnode/jobs/226585483).

**Comment by codeplea** [comment]
@dexcell Were you able to get it working?

**Comment by vaunus** [comment]
I am seeing the same issue and could not compile on macOS Sierra. It looks like in my case it is because of a space in the directory path when it comes to linking the binary so I'm guessing this is not escaped correctly.

Here is the appropriate section of the build log:
```
  SOLINK_MODULE(target) /Users/vreid/Documents/NodeJS Workspace/vbot/node_modules/tulind/lib/binding/Release/node-v48-darwin-x64/tulind.node
clang: error: no such file or directory: 'Workspace/vbot/node_modules/tulind/lib/binding/Release/node-v48-darwin-x64/tulind.node'
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
make: *** [/Users/vreid/Documents/NodeJS Workspace/vbot/node_modules/tulind/lib/binding/Release/node-v48-darwin-x64/tulind.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2```

After renaming the NodeJS Workspace directory to NodeJSWorkspace it managed to link the binaries and built successfully.
