### ISSUE TITLE
Order clarification

### ISSUE THREAD

**Issue by Vasile-Peste** [TulipCharts/tulipnode#65]
First of all I want to thank you for your work.
Just a question, sorry if it's obvious but I need a confirmation.
The README.md says that "Data order is from oldest to newset (index 0 is the oldest)".

This means that the result is also from the oldest to newest? Thanks.

```javascript
tulind.indicators.sma.indicator([close], [14], function(err, results) {
    console.log("Result of sma is:");
    // This is the oldest?
    console.log(results[0]);
});
```

Thanks.

**Comment by codeplea** [comment]
>This means that the result is also from the oldest to newest?

Yes, that is correct. Array element 0 is always the oldest data time-wise. All indicator calculations start at index zero are progress upwards.

Note that the output is often shorter than the input. In your example of sma with a period of 14, the result will be 13 elements shorter than the input. That's because you need the first 14 bars of input just to make the first output. After that, each input bar will produce an additional output bar. So the oldest data in the output is still index 0, but it would "line up" with the input at index 13. The last element in both the inputs and output both refer to the same bar, which is also the most newest bar time-wise.

For a concrete example, if you pass in 20 bars of input to sma with a period of 14, you'll get 7 outputs. output[0] matches up with input[13], whereas output[6] matches up to input[19], which is the newest data for each. So if you were charting indicators, you would always match up the ends of the arrays on your charts.

I hope that clears everything up. I should probably make a picture or something to explain this for the documentation. I know it can be a bit confusing at first.

**Comment by Vasile-Peste** [comment]
> > This means that the result is also from the oldest to newest?
> 
> Yes, that is correct. Array element 0 is always the oldest data time-wise. All indicator calculations start at index zero are progress upwards.
> 
> Note that the output is often shorter than the input. In your example of sma with a period of 14, the result will be 13 elements shorter than the input. That's because you need the first 14 bars of input just to make the first output. After that, each input bar will produce an additional output bar. So the oldest data in the output is still index 0, but it would "line up" with the input at index 13. The last element in both the inputs and output both refer to the same bar, which is also the most newest bar time-wise.
> 
> For a concrete example, if you pass in 20 bars of input to sma with a period of 14, you'll get 7 outputs. output[0] matches up with input[13], whereas output[6] matches up to input[19], which is the newest data for each. So if you were charting indicators, you would always match up the ends of the arrays on your charts.
> 
> I hope that clears everything up. I should probably make a picture or something to explain this for the documentation. I know it can be a bit confusing at first.

Clear, perfectly explained. Thanks!
